open Webapi.Dom
open Element

let el = document->Document.createElement("strong")
let el2 = document->Document.createElement("small")
let event = PointerEvent.make("my-event")

let _ = el->assignedSlot
let _ = el->attributes
let _ = el->classList
let _ = el->className
let _ = el->setClassName("my-class-name")
let _ = el->clientHeight
let _ = el->clientLeft
let _ = el->clientTop
let _ = el->clientWidth
let _ = el->id
let _ = el->setId("my-id")
let _ = el->innerHTML
let _ = el->setInnerHTML("<strong>stuff</strong>")
let _ = el->localName
let _ = el->namespaceURI
let _ = el->nextElementSibling
let _ = el->outerHTML
let _ = el->setOuterHTML("<strong>stuff</strong>")
let _ = el->prefix
let _ = el->previousElementSibling
let _ = el->scrollHeight
let _ = el->scrollLeft
let _ = el->setScrollLeft(0.0)
let _ = el->scrollTop
let _ = el->setScrollTop(0.0)
let _ = el->scrollWidth
let _ = el->shadowRoot
let _ = el->slot
let _ = el->setSlot("<strong>stuff</strong>")
let _ = el->tagName

let _ = el->attachShadow({"mode": "open"})
let _ = el->attachShadowOpen
let _ = el->attachShadowClosed
let _ = el->animate({"transform": "translateT(0px)"}, {"duration": 1000})
let _ = el->closest("input")
let _ = el->getAttribute("href")
let _ = el->getAttributeNS("http://...", "foo")
let _ = el->getBoundingClientRect
let _ = el->getClientRects->RectList.item(0)
let _ = el->getClientRects->RectList.toArray
let _ = el->getElementsByClassName("some-class-name")
let _ = el->getElementsByTagName("pre")
let _ = el->getElementsByTagNameNS("http://...", "td")
let _ = el->hasAttribute("data-my-value")
let _ = el->hasAttributeNS("http://...", "foo")
let _ = el->hasAttributes
let _ = el->insertAdjacentElement(BeforeBegin, el2)
let _ = el->insertAdjacentHTML(AfterBegin, "<strong>text</strong>")
let _ = el->insertAdjacentText(AfterEnd, "text")
let _ = el->matches("input")
let _ = el->querySelector("input")
let _ = el->querySelectorAll("input")
let _ = el->releasePointerCapture(PointerEvent.pointerId(event))
let _ = el->remove
let _ = el->removeAttribute("href")
let _ = el->removeAttributeNS("http://...", "foo")
let _ = el->requestFullscreen
let _ = el->requestPointerLock
let _ = el->scrollIntoView
/* let _ el->= scrollIntoViewNoAlignToTop; */
let _ = el->scrollIntoViewNoAlignToTop
let _ = el->scrollIntoViewWithOptions({"block": "end", "behavior": "smooth"})
let _ = el->setAttribute("href", "http://...")
let _ = el->setAttributeNS("http://...", "foo", "bar")
let _ = el->setPointerCapture(PointerEvent.pointerId(event))
