open Webapi.Dom
open Element

let el: t = document->Document.createElement("strong")
let el2: t = document->Document.createElement("small")
let event: PointerEvent.t = PointerEvent.make("my-event")

let assignedSlot: option<Dom.htmlSlotElement> = el->assignedSlot
let attributes: Dom.namedNodeMap = el->attributes
let classList: Dom.domTokenList = el->classList
let className: string = el->className
let setClassName: unit = el->setClassName("my-class-name")
let clientHeight: int = el->clientHeight
let clientLeft: int = el->clientLeft
let clientTop: int = el->clientTop
let clientWidth: int = el->clientWidth
let id: string = el->id
let setId: unit = el->setId("my-id")
let innerHTML: string = el->innerHTML
let setInnerHTML: unit = el->setInnerHTML("<strong>stuff</strong>")
let localName: string = el->localName
let namespaceURI: option<string> = el->namespaceURI
let nextElementSibling: option<t> = el->nextElementSibling
let outerHTML: string = el->outerHTML
let setOuterHTML: unit = el->setOuterHTML("<strong>stuff</strong>")
let prefix: option<string> = el->prefix
let previousElementSibling: option<t> = el->previousElementSibling
let scrollHeight: int = el->scrollHeight
let scrollLeft: float = el->scrollLeft
let setScrollLeft: unit = el->setScrollLeft(0.0)
let scrollTop: float = el->scrollTop
let setScrollTop: unit = el->setScrollTop(0.0)
let scrollWidth: int = el->scrollWidth
let shadowRoot: t = el->shadowRoot
let slot: string = el->slot
let setSlot: unit = el->setSlot("<strong>stuff</strong>")
let tagName: string = el->tagName

let attachShadow: Dom.shadowRoot = el->attachShadow({"mode": "open"})
let attachShadowOpen: Dom.shadowRoot = el->attachShadowOpen
let attachShadowClosed: Dom.shadowRoot = el->attachShadowClosed
let animate: Dom.animation = el->animate({"transform": "translateT(0px)"}, {"duration": 1000})
let closest: option<t> = el->closest("input")
let getAttribute: option<string> = el->getAttribute("href")
let getAttributeNS: option<string> = el->getAttributeNS("http://...", "foo")
let getBoundingClientRect: Dom.domRect = el->getBoundingClientRect
let clientRects: RectList.t = el->getClientRects
let getClientRectsItem: option<Dom.domRect> = el->getClientRects->RectList.item(0)
let getClientRectsArray: array<Dom.domRect> = el->getClientRects->RectList.toArray
let getElementsByClassName: Dom.htmlCollection = el->getElementsByClassName("some-class-name")
let getElementsByTagName: Dom.htmlCollection = el->getElementsByTagName("pre")
let getElementsByTagNameNS: Dom.htmlCollection = el->getElementsByTagNameNS("http://...", "td")
let hasAttribute: bool = el->hasAttribute("data-my-value")
let hasAttributeNS: bool = el->hasAttributeNS("http://...", "foo")
let hasAttributes: bool = el->hasAttributes
let insertAdjacentElement: unit = el->insertAdjacentElement(BeforeBegin, el2)
let insertAdjacentHTML: unit = el->insertAdjacentHTML(AfterBegin, "<strong>text</strong>")
let insertAdjacentText: unit = el->insertAdjacentText(AfterEnd, "text")
let matches: bool = el->matches("input")
let querySelector: option<t> = el->querySelector("input")
let querySelectorAll: Dom.nodeList = el->querySelectorAll("input")
let releasePointerCapture: unit = el->releasePointerCapture(PointerEvent.pointerId(event))
let remove: unit = el->remove
let removeAttribute: unit = el->removeAttribute("href")
let removeAttributeNS: unit = el->removeAttributeNS("http://...", "foo")
let requestFullscreen: unit = el->requestFullscreen
let requestPointerLock: unit = el->requestPointerLock
let scrollIntoView: unit = el->scrollIntoView
let scrollIntoViewNoAlignToTop: unit = el->scrollIntoViewNoAlignToTop
let scrollIntoViewWithOptions: unit = el->scrollIntoViewWithOptions({"block": "end", "behavior": "smooth"})
let setAttribute: unit = el->setAttribute("href", "http://...")
let setAttributeNS: unit = el->setAttributeNS("http://...", "foo", "bar")
let setPointerCapture: unit = el->setPointerCapture(PointerEvent.pointerId(event))
