type t = Dom.location

/* a more ergonomic API would perhaps accept a Window.t directly instead of Location.t */
@get external href: t => string = "href"
@set external setHref: (t, string) => unit = "href"
@get external protocol: t => string = "protocol"
@set external setProtocol: (t, string) => unit = "protocol"
@get external host: t => string = "host"
@set external setHost: (t, string) => unit = "host"
@get external hostname: t => string = "hostname"
@set external setHostname: (t, string) => unit = "hostname"
@get external port: t => string = "port"
@set external setPort: (t, string) => unit = "port"
@get external pathname: t => string = "pathname"
@set external setPathname: (t, string) => unit = "pathname"
@get external search: t => string = "search"
@set external setSearch: (t, string) => unit = "search"
@get external hash: t => string = "hash"
@set external setHash: (t, string) => unit = "hash"
@get external username: t => string = "username"
@set external setUsername: (t, string) => unit = "username"
@get external password: t => string = "password"
@set external setPassword: (t, string) => unit = "password"
@get external origin: t => string = "origin"

@send external assign: (t, string) => unit = "assign"
@send external reload: t => unit = "reload"
@send external reloadWithForce: (t, @as(json`true`) _) => unit = "reload"
@send external replace: (t, string) => unit = "replace"
@send external toString: t => string = "toString"
